"""
vision_utils.py — Helper functions for Multimodal RAG
Passes images to Ollama's Vision model to generate text summaries
that can be appended to the document's text context.
"""

import logging
import ollama
import io
import base64
from PIL import Image
from src.config import vision_model

logger = logging.getLogger(__name__)


def summarize_image(image_bytes: bytes) -> str:
    """
    Send an image to the local vision model and return a description.

    Args:
        image_bytes: The raw bytes of the image file (e.g., extracted from PDF or PPTX)

    Returns:
        A text description of the image content generated by the vision model.
    """
    try:
        img = Image.open(io.BytesIO(image_bytes))
        img.verify()
    except Exception as e:
        logger.warning("Skipping invalid image blob: %s", e)
        return ""

    try:
        b64_image = base64.b64encode(image_bytes).decode('utf-8')

        response = ollama.chat(
            model=vision_model(),
            messages=[{
                'role': 'user',
                'content': (
                    "You are an expert OCR text extractor and image analyzer. "
                    "First, accurately transcribe EVERY SINGLE WORD, title, axis label, and text "
                    "you can read in this image, chart, or diagram. State the text clearly. "
                    "Second, provide a detailed description of the diagram's structure, flow, or key takeaways."
                ),
                'images': [b64_image]
            }]
        )
        description = response.get('message', {}).get('content', '').strip()

        if description:
            return f"\n\n[Image/Diagram Description: {description}]\n"

    except Exception as e:
        logger.error("Ollama Vision API error (%s): %s", vision_model(), e)

    return ""
